import { Route, BrowserRouter as Router, Routes } from 'react-router-dom'
import MenuBookIcon from '@mui/icons-material/MenuBook'
import { Box, Typography } from 'decentraland-ui2'
import { NotFound } from './components/NotFound/NotFound'
import { StreamerView } from './components/StreamerView/StreamerView'
import { WalletButton } from './components/WalletButton/WalletButton'
import { WatcherView } from './components/WatcherView/WatcherView'
import { AuthProvider } from './context/AuthContext'
import { DocsLink } from './App.styled'

const HomePage = () => (
  <Box className="home-page">
    <Typography variant="h4">Decentraland Cast 2.0</Typography>
    <Typography variant="h6">Browser-native streaming with sub-second latency</Typography>
    <Typography variant="body1">Invalid route. Stream links are generated by the Admin Smart Item in Decentraland scenes.</Typography>
    <Typography variant="body2">
      <DocsLink href="https://docs.decentraland.org/creator/worlds/cast/" target="_blank" rel="noopener noreferrer">
        <MenuBookIcon />
        View Documentation
      </DocsLink>
    </Typography>
    <div className="auth-demo">
      <Typography variant="h6">Authentication Demo:</Typography>
      <WalletButton />
    </div>
  </Box>
)

const App = () => {
  return (
    <AuthProvider>
      <Router>
        <div className="app">
          <Routes>
            {/* Main routes for Cast 2.0 */}
            <Route path="/cast/s/:token" element={<StreamerView />} />
            <Route path="/cast/w/:roomId" element={<WatcherView />} />

            {/* Root redirects to home/invalid route handler */}
            <Route path="/" element={<HomePage />} />

            {/* 404 handler */}
            <Route path="*" element={<NotFound />} />
          </Routes>
        </div>
      </Router>
    </AuthProvider>
  )
}

export { App }
