name: Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: node.js 20
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: installing
        run: npm ci

      - name: lint
        run: npm run lint:check

      - name: test
        run: npm test
